def file_type_from_extension(filename: str) -> str | None:
    "https://www.computerhope.com/issues/ch001789.htm"
    associations = {
        "audio": {
            "aif": "AIF audio",
            "cda": "CD audio track",
            "mid": "MIDI audio file.",
            "midi": "MIDI audio file.",
            "mp3": "MP3 audio",
            "mpa": "MPEG-2 audio",
            "ogg": "Ogg Vorbis audio",
            "wav": "WAV",
            "wma": "WMA audio",
            "wpl": "Windows Media Player playlist",
        },
        "compressed": {
            "7z": "7-Zip compressed",
            "arj": "ARJ compressed",
            "deb": "Debian software package",
            "pkg": "Package",
            "rar": "RAR",
            "rpm": "Red Hat Package Manager",
            "tar": "z - Tarball compressed",
            "z": "Z compressed",
            "zip": "Zip compressed",
        },
        "disc image": {
            "dmg": "macOS X disk image",
            "iso": "ISO disc image",
            "toast": "Toast disc image",
            "vcd": "Virtual CD",
        },
        "data": {
            "csv": "Comma separated value",
            "dat": "Data",
            "log": "Log",
            "sav": "Save",
            "xml": "XML",
        },
        "database": {
            "db": ".dbf - Database",
            "mdb": "Microsoft Access database",
            "sql": "SQL database",
        },
        "email": {
            "email": "Outlook Express e-mail message file.",
            "eml": "E-mail message file from multiple e-mail clients, including Gmail.",
            "emlx": "Apple Mail e-mail file.",
            "msg": "Microsoft Outlook e-mail message file.",
            "oft": "Microsoft Outlook e-mail template file.",
            "ost": "Microsoft Outlook offline e-mail storage file.",
            "pst": "Microsoft Outlook e-mail storage file.",
            "vcf": "E-mail contact file.",
            
        },
        "executable": {  
            "apk": "Android package",
            "bat": "Batch",
            "bin": "Binary",
            "cgi": "Perl script",
            "pl": "Perl script",
            "com": "MS-DOS command",
            "exe": "Executable",
            "gadget": "Windows gadget",
            "jar": "Java Archive",
            "msi": "Windows installer package",
            "wsf": "Windows Script",
        },
        "image": {
            "ai": "Adobe Illustrator",
            "bmp": "Bitmap image",
            "gif": "GIF image",
            "ico": "Icon",
            "jpeg": ".jpg - JPEG image",
            "png": "PNG image",
            "ps": "PostScript",
            "psd": "PSD image",
            "svg": "Scalable Vector Graphics",
            "tif": ".tiff - TIFF image",
            "webp": "WebP image.",
        },
        "source code": {
            "css": "Cascading Style Sheet",
            "htm": ".html - HTML",
            "js": "JavaScript",
            "c": "C and C++ source code",
            "cpp": "C++ source code",
            "cs": "Visual C# source code",
            "h": "C, C++, and Objective-C header",
            "java": "Java Source code",
            "php": "PHP script file.",
            "py": "Python script file.",
            "sh": "Bash shell script",
            "swift": "Swift source code",
            "vb": "Visual Basic",
            "rs": "Rust",
        },
        "spreadsheet format": {
            "ods": "OpenOffice Calc spreadsheet",
            "xls": "Microsoft Excel",
            "xlsm": "Microsoft Excel file with macros",
            "xlsx": "Microsoft Excel Open XML spreadsheet",
        },
        "video": {
            "3g2": "3GPP2 multimedia",
            "3gp": "3GPP multimedia",
            "avi": "AVI",
            "flv": "Adobe Flash",
            "h264": "H.264 video",
            "m4v": "Apple MP4 video",
            "mkv": "Matroska Multimedia Container",
            "mov": "Apple QuickTime movie",
            "mp4": "MPEG4 video",
            "mpg": ".mpeg - MPEG video",
            "rm": "RealMedia",
            "swf": "Shockwave flash",
            "vob": "DVD Video Object",
            "webm": "WebM video file.",
            "wmv": "Windows Media Video",
        },
        "text": {
            "doc": ".docx - Microsoft Word",
            "odt": "OpenOffice Writer document",
            "pdf": "PDF",
            "rtf": "Rich Text Format",
            "tex": "A LaTeX document",
            "txt": "Plain text",
            "wpd": "WordPerfect document",
        }
    }
    if not "." in filename:
        return
    extension = filename.split(".")[-1]
    for category, extension_mapping in associations.items():
        if extension in extension_mapping:
            return f"{category} ({extension_mapping[extension]})"
