version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: container-registry.oracle.com/mysql/community-server:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
